# Generated by Django 5.1.4 on 2025-01-05 16:57

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('image', models.ImageField(blank=True, help_text='Необязательно. Нужно подтвердить дважды', verbose_name='Изображение ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
