# Generated by Django 5.1.4 on 2025-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_priority_remove_task_date_task_change_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='Дедлайн (срок)'),
        ),
    ]
