# Generated by Django 5.1.4 on 2025-01-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_priority_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
