# Generated by Django 5.1.3 on 2025-01-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='change_date',
        ),
    ]
